name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "AllianceAuth Version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            type=semver,pattern={{version}},value=${{ inputs:version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs:version }}
            type=semver,pattern={{major}},value=${{ inputs:version }}

      - name: Build the Docker image
        run: echo ${{ steps.meta.outputs.tags }}
