name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "AllianceAuth Version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          REGISTRY_PREFIX=ghcr.io/Maestro-Zacht/allianceauth-docker-pypy
          CURRENT_TAG=$REGISTRY_PREFIX:${{ inputs.version }}
          MINOR_TAG=$REGISTRY_PREFIX:$(echo $CURRENT_TAG | cut -d '.' -f 1-2)
          MAJOR_TAG=$REGISTRY_PREFIX:$(echo $CURRENT_TAG | cut -d '.' -f 1)
          LATEST_TAG=$REGISTRY_PREFIX:latest

          docker build . -t $CURRENT_TAG --build-arg AUTH_VERSION=${{ inputs.version }}
          docker tag $CURRENT_TAG $MINOR_TAG
          docker tag $CURRENT_TAG $MAJOR_TAG
          docker tag $CURRENT_TAG $LATEST_TAG
          docker image push --all-tags ghcr.io/Maestro-Zacht/allianceauth-docker-pypy
