name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "AllianceAuth Version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          REGISTRY_PREFIX=ghcr.io/maestrozacht/authpypy
          CURRENT_TAG=$REGISTRY_PREFIX:${{ inputs.version }}
          MINOR_TAG=$REGISTRY_PREFIX:$(echo ${{ inputs.version }} | cut -d '.' -f 1-2)
          MAJOR_TAG=$REGISTRY_PREFIX:$(echo ${{ inputs.version }} | cut -d '.' -f 1)
          LATEST_TAG=$REGISTRY_PREFIX:latest

          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build . -t $CURRENT_TAG --build-arg AUTH_VERSION=${{ inputs.version }}
          docker tag $CURRENT_TAG $MINOR_TAG
          docker tag $CURRENT_TAG $MAJOR_TAG
          docker tag $CURRENT_TAG $LATEST_TAG
          docker image push --all-tags $REGISTRY_PREFIX
