name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "AllianceAuth Version"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: maestro-zacht/authpypy
  IMAGE_TAG: ${{ inputs.version }}

jobs:
  test:
    name: "Test PyPy image"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pypy-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image tests
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          target: "test"
          build-args: |
            "AUTH_VERSION=${{ env.IMAGE_TAG }}"
            "PYPY_VERSION=${{ matrix.pypy-version }}"

  publish:
    name: "Publish PyPy image"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    needs: [test]

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=v{{version}},value=${{ env.IMAGE_TAG }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ env.IMAGE_TAG }}
            type=semver,pattern=v{{major}},value=${{ env.IMAGE_TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          target: "prod"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "AUTH_VERSION=${{ env.IMAGE_TAG }}"
