name: Docker Image CI

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: maestrozacht/allianceauth-docker-pypy
  IMAGE_TAG: ${{ context.GITHUB_REF }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: test
        run: echo "${{ env.IMAGE_TAG }}"

      # - name: Check out the repo
      #   uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
