name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "AllianceAuth Version"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: maestro-zacht/authpypy
  IMAGE_TAG: ${{ inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=v{{version}},value=${{ env.IMAGE_TAG }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ env.IMAGE_TAG }}
            type=semver,pattern=v{{major}},value=${{ env.IMAGE_TAG }}

      - name: print tags
        run: echo "${{ steps.meta.outputs.tags }}"

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "AUTH_VERSION=${{ env.IMAGE_TAG }}"
